const constants = {
    TASK_REORDER_START: `TASK_REORDER_START`,
    TASK_REORDER_SUCCESS: `TASK_REORDER_SUCCESS`,
    TASK_REORDER_ERROR: `TASK_REORDER_ERROR`,

    TASK_ON_SELECT: `TASK_ON_SELECT`,
    TASK_FIND_START: `TASK_FIND_START`,
    TASK_FIND_SUCCESS: `TASK_FIND_SUCCESS`,
    TASK_FIND_ERROR: `TASK_FIND_ERROR`,

    TASK_UPDATE_START: `TASK_UPDATE_START`,
    TASK_UPDATE_SUCCESS: `TASK_UPDATE_SUCCESS`,
    TASK_UPDATE_ERROR: `TASK_UPDATE_ERROR`,
};
export default constants;
