const constants = {
    COLUMN_CREATE_START: `COLUMN_CREATE_START`,
    COLUMN_CREATE_SUCCESS: `COLUMN_CREATE_SUCCESS`,
    COLUMN_CREATE_ERROR: `COLUMN_CREATE_ERROR`,

    COLUMN_FIND_START: `COLUMN_FIND_START`,
    COLUMN_FIND_SUCCESS: `COLUMN_FIND_SUCCESS`,
    COLUMN_FIND_ERROR: `COLUMN_FIND_ERROR`,

    COLUMN_REORDER: `COLUMN_REORDER`,
};
export default constants;
