const constants = {
    BOARD_GET_LIST_SUCCESS: `BOARD_GET_LIST_SUCCESS`,

    BOARD_CREATE_START: `BOARD_CREATE_START`,
    BOARD_CREATE_SUCCESS: `BOARD_CREATE_SUCCESS`,
    BOARD_CREATE_ERROR: `BOARD_CREATE_ERROR`,

    BOARD_FIND_START: `BOARD_FIND_START`,
    BOARD_FIND_SUCCESS: `BOARD_FIND_SUCCESS`,
    BOARD_FIND_ERROR: `BOARD_FIND_ERROR`,
};
export default constants;
